services:
  - type: web
    name: saini-txt-direct
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/iryme786/saini-txt-direct
    branch: main
    autoDeploy: false
